export enum BUTS_MATCH {
    ZERO_BUT = '0 BUT',
    ONE_BUT = '1 BUT',
    TWO_BUT = '2 BUTS',
    THREE_BUT = '3 BUTS',
    FOUR_BUT = '4 BUTS ET +'
 }
export enum MOYENNE_STATS {
    TIRS = 'TIRS',
    TIRS_CADRES = 'TIRS CADRES',
    CORNERS = 'CORNERS',
    FAUTES = 'FAUTES',
    CARTONS_JAUNE = 'CARTONS JAUNE',
    CARTONS_ROUGE = 'CARTONS ROUGE'
 }
export enum SCORE_FINAL {
    VICTOIRE = 'VICTOIRE',
    NUL = 'NUL',
    DEFAITE = 'DEFAITE'
 }
export enum SEASON_GENERIC {
     GOALS_FOR = 'BUT POUR',
     SHOTS_FOR = 'TIRS POUR',
     XG_FOR = 'XG POUR',
     GOALS_AGAINST = 'BUT CONTRE',
     SHOTS_AGAINST = 'TIRS CONTRE',
     XG_AGAINST = 'XG CONTRE'
 }
export enum GAME_STAT {
    GOALS_FOR = 'BUT POUR',
    SHOTS_FOR = 'TIRS POUR',
    XG_FOR = 'XG POUR',
    GOALS_AGAINST = 'BUT CONTRE',
    SHOTS_AGAINST = 'TIRS CONTRE',
    XG_AGAINST = 'XG CONTRE',
    TIME = 'DUREE'
}

